[package]
name = "loonar-screech"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
cpal = "0.15"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
rodio = "0.16"
rand = "0.8"
anyhow = "1.0"
libc = "0.2"